### ISSUE TITLE
Zone suggestion

### ISSUE THREAD

**Issue by vkichline** [ropg/M5Core2#11]
If you defined special zones that represented the edges of the screens, it would be easier to indicate that a swipe in or swipe out is intended, and the code would be able to identify that intention and possibly apply heuristics for identifying those gestures.
For example:
```
Zone topEdge(0, 0, 320, 0);
```
Just a suggestion, but it could make improvements possible in the future w/o having to change client code.

**Comment by ropg** [comment]
Yeah, but the zone would need to be 30-40 pixels wide or so, or t will miss it. There's only a sample every 13 ms, so it can skip right over it... One could even have premade gestures that only activate when there's a handler for them. You gotta stop somewhere...
