### ISSUE TITLE
Concern: overly general define names

### ISSUE THREAD

**Issue by vkichline** [ropg/M5Core2#16]
Rop:
It seems like using names like BUTTON_TEXTFONT, TAP_TIME, NUM_EVENTS, etc. in a system header file is dangerous and is likely to lead to collisions. I already reported one with ezTime at (community.m5stack.com)[https://community.m5stack.com/topic/2306/m5core2-library-fork-that-supports-multi-touch-and-provides-arduino-style-virtual-buttons-update-and-gestures-and-events-update2-merged/44].
Suggestion: Prefix all header defines with M5. I'm unlikely to start a define with that in my code, unless I'm writing something to be compatible with several platforms (which I generally don't.)

It would be a lot better (in my opinion) if the event types were an enum. You can use something like:
typedef enum M5EventType {
    E_TOUCH = 0x0001,
    E_RELEASE = 0x0002,
    E_MOVE = 0x0004,
    ... etc.
} M5EventType;

**Comment by ropg** [comment]
The problem with that is that you can't just add them together anymore, or subtract them from E_ALL, no?

(I guess one could overload addition, subtraction and the binary operators, but but but...)

**Comment by vkichline** [comment]
Sorry, I spent years in C#, where enums like this are common.
I have to keep typing things out in C++ to be sure I haven't blended the syntaxes together in my head.
Too bad, using enums like this is really convenient. Some future C++, I'm sure.
