### ISSUE TITLE
addHandler/delHandlers

### ISSUE THREAD

**Issue by vkichline** [ropg/M5Core2#17]
The functions:
```
  void addHandler(void (*fn)(Event&), uint16_t eventMask = E_ALL);
  void delHandlers(void (*fn)(Event&) = nullptr);
```
...don't seem symmetrical. I would prefer `delHandler()`.  I see from the signature it's likely to remove all handlers as well as a special case, but if I'm examining the API through IntelliSense (as in PlatformIO) I see no `delHandler` function, and `delHandlers` is clearly for all handlers, so I have to turn to the docs.
If I intend to delete all handlers, it's not hard to land on `delHandler`.

**Comment by ropg** [comment]
`delHandlers` on the `Buttons` object is versatile in that you can specify the function and/or button and/or gesture, and if you leave any off it will take that as `ANY`. So it deserves that name, I think. The name for that on `Button` and `Gesture` is just that way for consistency, I guess. It just bounces through to the `Buttons` one with the right object filled in. just wanted to make clear it might delete multiple handlers. (It was written for the destructor. Honestly don't think many people will use this, esp. after we have a way to hide the buttons.)

**Comment by vkichline** [comment]
Not a big deal. I found I did use it in TouchView.
I easily remembered the pluralization, but typed removeHandlers(), so I had to look it up anyway.
But you're right, not common enough to be concerned about.
