### ISSUE TITLE
class TFT_eSPI_Button

### ISSUE THREAD

**Issue by vkichline** [ropg/M5Core2#20]
I appreciate that this class is aimed at x-device compat, but since this is an M5-specific library file (with M5Events and M5Buttons) it doesn't seem like a hard-to-type class name needs to be in such a useful position.
I suggest `class VisualButton`. It's clear what is is, it rolls off the tongue (and out of memory), and is just as portable.

TFT_eSPI_ names are fine when they're not at the tip of the hierarchy.

**Comment by ropg** [comment]
How is it in your way? it's just there for people that want to run software made for ESPs and resistive touch screens. You'd never use this in new code, you'd use 'Button', which is all the visual you need.

**Comment by vkichline** [comment]
Sorry, I thought this was for routine consumption. Docs now make it clear it is not.
