### ISSUE TITLE
Hide and Show Buttons?

### ISSUE THREAD

**Issue by vkichline** [ropg/M5Core2#21]
I may have missed it, but I don't see any way to hide and show buttons.
This can be a very useful technique. Hidden buttons shouldn't take touches.

I realize this is hard to reconcile with hardware buttons, but very desirable for visual elements.

**Comment by ropg** [comment]
You can make them go out of scope or new/delete the variables. Visually hiding means I'd need to know what was underneath or store a delete color.

How about `void hide(uint16_t color = NODRAW);` that draws that color if specified and sets some kind of hidden flag to make it not accept touches anymore, and `draw()` also unhides?

**Comment by ropg** [comment]
feature introduced.
