### ISSUE TITLE
Functional issue: events_buttons_gestures_rotation exhibits incorrect selection in rotation

### ISSUE THREAD

**Issue by vkichline** [ropg/M5Core2#22]
Using version ffbc898:
1. Run events_buttons_gestures_rotation
2. Double-tap top-left button. Turns blue. Good.
3. Swipe up. Display inverts. Good.
4. Double-tap button named "top-left" (now at bottom-right.) Button named "bottom-left" (in top-right position) becomes blue. Error.
5. Double-tap button labeled "bottom-left" (in top-right position). Nothing happens. Error.

Similar issues exist with double-tapping left and right rotated screens as well.
For all rotations try:
Rotate, double-tap top-right position, double-tap bottom right position.

**Comment by ropg** [comment]
fixed (Thought to use existing #defines only to find that the TFT driver thinks this display is 240 wideand 320 high, i.e. portrait.
