### ISSUE TITLE
Suggestion: showABC(), hideABC()

### ISSUE THREAD

**Issue by vkichline** [ropg/M5Core2#29]
Your example of displaying the A, B, C button labels in M5Button.h, line 284, looks like one of those super-useful magical incantations that users always have to look up in order to use. I do this with several useful phrases too often, here is a chance to eliminate one more!
Have you considered adding the function showABC() which does exactly what you show here, and possibly an inverse hideABC()? Be sure to add them to keywords.txt, because I think they'd be used often.

**Comment by ropg** [comment]
Hmmm, see what you mean, but then you'd also want to provide names for the buttons. And then we have M5ez...

(For which I have some amazing ideas now. Among other things: sprites for header, canvas and buttons!)

**Comment by ropg** [comment]
Leaving this one for now...
