### ISSUE TITLE
Additional gestures?

### ISSUE THREAD

**Issue by vkichline** [ropg/M5Core2#3]
Running the demo, I never see an `E_LONGPRESSING` or `E_LONGPRESSED` event.  
`LONGPRESS_TIME` is set to zero. Is this the right value?

If one were to grab (via a long press) and drag/drop an item on the screen, I would expect a sequence of events like:
E_TOUCH
E_PRESSING
E_LONGPRESSING
E_MOVE
E_MOVE
E_MOVE
E_RELEASED
E_DRAGGED

Move events would allow the UI to animate dragging an object (or a dotted outline) around the screen.

**Comment by ropg** [comment]
Yes, it needs to be set to something other than zero before anything happens. It and repeatDelay are somewhat mutually exclusive.
