### ISSUE TITLE
Possible doc issue

### ISSUE THREAD

**Issue by vkichline** [ropg/M5Core2#30]
M5Button.h, line 352, for clarity:
"Note that the function name is provided without the brackets."
You might add "the function name in addHandler" for those unfamiliar with this concept.

Also, again this might be an Americanism, but we would specifically refer to () as parenthesis. Brackets would refer specifically to []. Again, I'm concerned about those who are already confused getting more confused.
If international punctuation naming poses conflicts, one could use concrete examples (use "()" instead of the name.)

**Comment by ropg** [comment]
fixed
