### ISSUE TITLE
Doc omission: setting E_LONGPRESSED time

### ISSUE THREAD

**Issue by vkichline** [ropg/M5Core2#35]
M5Button.h, section starting at line 395: E_TAP, E_DBLTAP, E_PRESSED, E_LONGPRESSED and E_DRAGGED

This section says "E_LONGPRESSED fires if the key was pressed more that the set time in ms."
However, it it not set initially, and this doesn't tell me how to set it. I was looking for that in particular once I found out that TouchGoal could detect this and doesn't.

Suggestion:
E_LONGPRESSED fires if the key was pressed more that the set time in ms, which is set by calling ???
I still can't find where that's set, but haven't devoted more than a couple minutes to it.

**Comment by vkichline** [comment]
Found it! just a simple, unadorned public longPressTime.
The multiple definitions on a single line make it more difficult to spot (for me.)

**Comment by ropg** [comment]
Added section to manual

```text
== Taps, Doubletaps, Longpresses and Key Repeat ==

  Some features are best explained with some examples:

    myButton.tapTime = 0;

      Turns off detection of taps and doubletaps, the button will fire become
      E_PRESSING immediately. Any other value makes that the maximum time a
      tap can take in milliseconds, and thus the wait tme before "E_PRESSING"
      fires.

    mybutton.tapWait = 0;

      Turns off detection of doubletaps only. Any other value makes that the
      wait before an E_TAP fires, because M5Button is still waiting to see if
      it's a maybe a doubletap.

    mybutton.longPressTime = 700;

      Sets up the button to fire an E_LONGPRESSING after 700 ms, and then fire
      E_LONGPRESSED instead of E_PRESSED when the button is released. By
      default this is set to zero, meaning longpress detection is off.

    myButton.repeatDelay = 500;
    myButton.repeatInterval = 250;

      Makes the button repeat the sending of its E_PRESSING event every 250
      milliseconds if key is held for 500 ms.
```
