### ISSUE TITLE
Doc question

### ISSUE THREAD

**Issue by vkichline** [ropg/M5Core2#36]
Reading the section of M5Button.h starting at line 451: e.button and e.gesture
Can these pointers be null? If so, you might mention that they should be tested before they're used.
If not, couldn't they be references as well? The semantics of the event handler is reference based, and these are likely to be used most in that context.

**Comment by ropg** [comment]
The button pointer always at least points to M5.background. Gesture should be tested unless you are attached to a gesture or triggering on E_GESTURE only. Fixed.
