### ISSUE TITLE
Doc error!

### ISSUE THREAD

**Issue by vkichline** [ropg/M5Core2#47]
PointAndZone.h, line 18:
"Values -1 for x and y indicate an invalid value"

Yet another reason to hate magic numbers. Suggest: "The value INVALID_VALUE for x or y indicate..."

Code error?
Line 155: void set(int16_t x_ = -1, int16_t y_ = -1);
Shouldn't this be: void set(int16_t x_ = INVALID_VALUE, int16_t y_ = INVALID_VALUE);

**Comment by ropg** [comment]
yup, fixed...
