### ISSUE TITLE
Overly general #defines

### ISSUE THREAD

**Issue by vkichline** [ropg/M5Core2#51]
In PointAndZone.h, the #defines UP, RIGHT, DOWN and LEFT may be too general to inject into every M5 program.

I'm not sure what to prefix them with; you could clarify their meaning a little (and you understand their context best) or you could just add M5.

**Comment by ropg** [comment]
DIR_LEFT ... etc.
DIR_ANY (a.k.a. INVALID_VALUE) for no direction
