### ISSUE TITLE
TFT_eSPI Resistive Touch API emulation is vague

### ISSUE THREAD

**Issue by vkichline** [ropg/M5Core2#58]
In M5Touch.h, the section starting on line 156: == TFT_eSPI Resistive Touch API emulation ==
...seems vague to me. I'm not sure what the interface is or where it's implemented. It's named in the docs.
Maybe I am getting tired and missed something, but I rarely go "huh?" when reading your docs!

**Comment by ropg** [comment]
They are [new functions](https://github.com/ropg/M5Core2/blob/master/src/M5Display.h#L121) in the M5Display class. It does say "While technically not part of this library itself, we added an emulation for the TFT_eSPI touch API to the M5Display object that merely passes informaton on to the M5.Touch object "

Open to better ways of saying this...

**Comment by vkichline** [comment]
I reread this today, and either you changed it a little or I needed rest. Seems clear enough to me.
