### ISSUE TITLE
Doc omission: M5Buttons

### ISSUE THREAD

**Issue by vkichline** [ropg/M5Core2#63]
I see one mention of the M5Buttons defined in M5Buttons.h, but no documentation on how or when it's used.
It looks like this is something I would use; if it's just internal, some comments to that effect near the declaration would keep me from looking for more info.

**Comment by ropg** [comment]
Uh... No idea what you're talking about here...

Could be bc I just fixed a gazillion issues.... :)

**Comment by vkichline** [comment]
I left a word out, I was referring to the M5Buttons **class** defined at the bottom of M5Button.h, line 919 in current version.
The only direct reference to it is in Advanced Hints and Tricks; drawFn.
But I see now that I'm well rested that this appears to be a singleton class, created by the system and is where I can hook up general handlers, etc., but I don't even know how I know that. Search the docs for M5Buttons: it's really not there.
If it's a class only used by the system and the user doesn't have to be aware of it, you can add a comment to that effect inline where it's defined.
But if you learn by reading, you get to this class at the pinnacle of M5Button header, and it looks key to using the feature; then you search the docs for it and it seems like it's inky used for setting the drawFunction.
I feel like I'm missing something. Maybe the docs just need to tell me "don't worry about M5Buttons, you will only use it for..."

**Comment by ropg** [comment]
New little section:

```text
== M5.Buttons ==

  Apart from the class "Button" that you use to create buttons of your own,
  there is an instance called "M5.Buttons" (plural), that is used to talk to
  the M5Button library for things that involve all buttons. For instance:
  "M5.Buttons.setFont" sets a font for all buttons, and you can use
  "M5.Buttons.addHandler" to add a handler that gets events for all buttons
  (and gestures). 
```

**Comment by vkichline** [comment]
Looks good! I would still include "an instance of the M5Buttons class" even though it seems obvious, just because I was searching for mentions of M5Buttons everywhere, working backwards. I hadn't tied it together in my mind that M5.Buttons was an M5Buttons (believe it or not.) Somehow that just didn't click.  Seems obvious now, but when search only finds the source code, it's frustrating.
I guess it's just that the concept count is high, so my mind stopped making connections until it had all the facts. Second read would probably clarify it.
