### ISSUE TITLE
New doc issue

### ISSUE THREAD

**Issue by vkichline** [ropg/M5Core2#66]
I like the section on == Taps, Doubletaps, Longpresses and Key Repeat ==, makes it very clear!
However, line 523:
"the button will fire become E_PRESSING immediately"
should be
"the button will fire becoming E_PRESSING immediately"

line 532/532:
"because M5Button is still waiting to see if it's a maybe a doubletap."
should be
"because M5Button is still waiting to see if it's maybe a doubletap."

**Comment by ropg** [comment]
Both fixed...

Thanks so much for all the work you're putting in... Will do PR today.
