### ISSUE TITLE
Point class issue

### ISSUE THREAD

**Issue by vkichline** [ropg/M5Core2#8]
Since the Point class has a `valid()` member function, there's no need to define that -1,-1 is invalid.
I recommend changing x & y to uint16_t's, (the native type of all the other TFT dimensions), adding a private `_valid` flag, and adding a public `invalidate()` function.
There's no need to possibly cope with lots of data conversion warnings of uint16_t and int16_t when it's not needed.
I need not compare to a magic value when I have a `valid()` function.

**Comment by ropg** [comment]
I changed -1, -1 to -32768, -32768, a.k.a `INVALID_VALUE`, because -1, -1 might be a working value in some cases.

We certainly need negative values, as, for instance, the below screen buttons are at negative Y-values in rotation 3 (upside down)
